name: Pandoc Conversion

on:
  push:
    branches:
      - main 
      
jobs:
  pandoc_conversion:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Ensure the entire history is fetched, required for fetching submodules

    - name: Install Pandoc and LaTeX packages
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-latex-recommended texlive-xetex texlive-luatex

    - name: Convert HTML to PDF
      run: |
        pandoc --pdf-engine=xelatex presentation.html -s -o presentation.pdf
